### ISSUE TITLE
example does not work

### ISSUE THREAD

**Issue by nkoerb** [guilhermebs/CondaNSIS#1]
Hey, 

I tried the example from the docs, but unfortunately it does not work:

windows server 2012
Python 3.7 

snake.py
```
import time
SNAKE = r"""
                          ____
 ________________________/ O  \___/
<_____________________________/   \
"""

if __name__ == "__main__":
    print(SNAKE)
    time.sleep(10)

```
installer.py
```

from pathlib import Path
import condansis

if __name__ == "__main__":
    this_dir = Path(__file__).parent

    # instantiate Installer
    installer = condansis.Installer(
        package_name="snake-simulator",
        package_root=this_dir,
        package_version="1.0",
        include=["resources"],
        icon=Path("resources", "snake.ico"),
    )

    # Create a shortcut in the snake.exe entrypoint
    # In the target computer, entrypoints can be found at
    # $INSTDIR\$ENV\Scripts
    installer.add_shortcut(
        shortcut_name=Path("$INSTDIR", "snake.lnk"),
        target_file=Path("$INSTDIR", "$ENV", "Scripts", "snake.exe"),
        icon_file=Path("$INSTDIR", "resources", "snake.ico"),
    )

    # Create the installer
    installer.create()
```

  File "...\installer example\installer.py", line 34, in <module>
    installer.create()

  File "...\lib\site-packages\condansis\installer.py", line 354, in create
    self.create_temp_env(env_prefix)

  File "...\lib\site-packages\condansis\installer.py", line 221, in create_temp_env
    check=True,

  File "...\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:

  File "...\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)

  File "...\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)

  File "...\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg

TypeError: argument of type 'WindowsPath' is not iterable

Thanks for your help!

**Comment by guilhermebs** [comment]
Hello,
Thanks a lot for raising this issue. CondaNSIS is only compatible with `python>=3.8`. The README and the environment have been changed to reflect that. It is also important to say that, despite CondaNSIS requiring `python>=3.8`, it can build python apps that use older python versions.
Also a clarification, the `installer.py` file you posted creates the installer for the example  _package_, it does not work with the example snake.py script .

**Comment by PeterSR** [comment]
I ran into the same problem. And readme and docs does not seem to reflect this issue. 

I fixed it locally by editing the `condansis` source code. In the `condansis/installer.py`, I found all references to `subprocess` (4 in total) and wrapped all parts of the `args` list in `str(...)`. Example:

```python
        subprocess.run(
            [self.makensis_exe, script_name], check=True,
        )
```

to

```python
        subprocess.run(
            [str(self.makensis_exe), str(script_name)], check=True,
        )
```

**Comment by guilhermebs** [comment]
Hi Peter, thanks for the suggestion. I have just pushed the changes you suggested (https://github.com/guilhermebs/CondaNSIS/pull/3)  as they seem to be more stable approach, even though I can't reproduce the error.

**Comment by PeterSR** [comment]
Thank you! That's awesome!
